local x = {
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	basht = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 8,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
	default = {
		usability = 0,
		documentation = 0,
		configuration = 0,
		keybinds = 0,
		speed = 0,
		plugins = 0,
		features = 0,
		updates = 0,
		preview = 0,
		theming = 0,
		influence = 0,
		uniqueness = 0,
	},
}

-- this is bad code, but lazy code, but still bad code
for project, ranks in pairs(x) do
	print(project)

	local usability = ranks.usability * 10
	local documentation = ranks.documentation * 10
	local configuration = ranks.configuration * 9
	local keybinds = ranks.keybinds * 9
	local speed = ranks.speed * 8
	local plugins = ranks.plugins * 8
	local features = ranks.features * 7
	local updates = ranks.updates * 5
	local preview = ranks.preview * 5
	local theming = ranks.theming * 4
	local influence = ranks.influence * 4
	local uniqueness = ranks.uniqueness * 4

	print("usability: " .. usability)
	print("documentation: " .. documentation)
	print("configuration: " .. configuration)
	print("keybinds: " .. keybinds)
	print("speed: " .. speed)
	print("plugins: " .. plugins)
	print("features: " .. features)
	print("updates: " .. updates)
	print("preview: " .. preview)
	print("theming: " .. theming)
	print("influence: " .. influence)
	print("uniqueness: " .. uniqueness)

	print(
		"average: "
			.. (
					usability
					+ documentation
					+ configuration
					+ keybinds
					+ speed
					+ plugins
					+ features
					+ updates
					+ preview
					+ theming
					+ influence
					+ uniqueness
				)
				/ 83
	)
	print("\n")
end
